#!/bin/bash
# Docker image cleanup script - generated by gen_docker_rmi.py
# Total targets: 364 (140 dangling + 224 old tagged)
# Estimated space to free: ~336.5 GB
#
# Usage: bash scripts/docker_cleanup.sh
# Review first: cat scripts/docker_cleanup.sh

echo "=========================================="
echo "Docker Image Cleanup"
echo "=========================================="
echo ""
echo "This will remove:"
echo "  - 140 dangling images (<none> tag)"
echo "  - 224 old version images"
echo "  - Estimated space to free: ~336.5 GB"
echo ""
echo "Keeping 79 newest images (1 per repo, 6 for ns-robot)"
echo ""
read -p "Continue? (yes/no): " confirm
if [ "$confirm" != "yes" ]; then
  echo "Aborted."
  exit 0
fi

echo ""
echo "Removing images..."
echo ""

docker rmi \
  060502b1c38f 070d806904fe 0847ebe5e385 08721dafd45d 0dcf823a73ab \
  10cc060f288a 15ca397262dc 17da604fa553 1c4d0955996f 1f7747f42740 \
  22877a6a2871 2319000e3204 252b7fbcb3a6 25fac79e85b7 2af5917beca4 \
  2d6336645b82 2f64392e588b 30df18c54f97 31bf25dcb172 345f4be99721 \
  39c8d7952e70 3b9a792e8e00 3cef9fc0f711 3e74741c58dd 3f53f18add0f \
  405789890af5 405dedbcd7a4 413fa4d0b96f 4693f1623e2f 46a0e4002ee4 \
  47c6f54526fb 47fdb769cdfa 489db4843a5f 48cb6f528549 511ca78867c7 \
  519c2c0be59a 5422f959eacc 54eda7dc9587 573401b4d479 57497218175c \
  584d7201ef0f 5ca7c8c11a7b 5e23061c10c5 5f4d69d54d1b 611f94d5afb9 \
  65516fb193bb 68effb42501c 691b8e251653 6ba76c91d52d 6d1018f2c9cc \
  6e33d3a21c3c 6e4e0c2d158c 6edb89793c85 724d5fb988be 724dc08d5aef \
  72db74e5349f 72e216ae9bff 737943219a40 77d980b85e17 79002f14a25c \
  79883429e844 7ad4e0b957b9 7cb9bb716f8e 7fb180f306aa 86b35846b56c \
  8a0a940a8e3b 8b1b94cd8003 8ffe69bb4ab5 90c7d7ca3dce 932829021158 \
  96ac3b33aacc 96d4e640115e 97f6c9179820 98bd85732347 9ad3ce911174 \
  a0138e543ae9 a06b0865d04d a16eeef3e8fc a32ede690edc a972ae053e4c \
  a9ac51546b14 aac764379cd1 aaf268c923ca ae4c89429fa5 b1924934a086 \
  b29832093341 b3242ac19931 b588fcc937bc b77e64f06f6b b894c4fd50f8 \
  bc64b9379f48 bef7102dd283 c284ab39b9f1 c36abf802805 c4f1728d498e \
  c724acdb890c c746df08995e caee89d5958b cbacc172236e cbcfec7df7c3 \
  cc0764daea61 cc569545af91 cc6068444df9 cca262cbd403 cccd65b3f6d6 \
  ce0ed809f667 cf6dab2071d3 d0ea710bf2be d10c9660c324 d12ede206eb9 \
  d17c17b62c7a d17e6e61714c d2b972d25a6b d41344606cad d52409726b91 \
  d5af678d6b55 dbdb6a2dd799 de8999407228 df007086543f e03746490b61 \
  e28ad43d2f53 e30bb045005c e3b17f13fa44 e614a979a7ee e70589a72ff2 \
  e7ec31e44544 e8f86f0b8427 eaea3d043d25 ec554778c9f9 ee0bf90aeacc \
  effbfe667223 f2d142500db3 f8499ecbdda4 fa9c69a6c2f5 fb0e9f34b147 \
  fbf617341957 fca0d26f63cf fdffae20f7b9 ff7a6e6af15b ff7c1bbdd7c2 \
  moby/buildkit:v0.12.5 \
  ns-pdf-server:1.0-7a0c39f098 \
  ns-robot:1.0-13182650cc ns-robot:1.0-2380a65c09 ns-robot:1.0-37443aaa26 \
  ns-robot:1.0-41d712307c ns-robot:1.0-499a83313e ns-robot:1.0-6a2a0fc869 \
  ns-robot:1.0-6fb6b6f9c8 ns-robot:1.0-8527760e44 ns-robot:1.0-a16d56b276 \
  ns-robot:1.0-ae2faafed5 ns-robot:1.0-bca1ef1a99 ns-robot:1.0-c1ff482c27 \
  ns-robot:1.0-c6341f9e9f ns-robot:1.0-e557fd5692 ns-robot:1.0-eaa84f3822 \
  swr.cn-north-4.myhuaweicloud.com/ns-release/ns-pdf-server:1.0-7a0c39f098 \
  swr.cn-north-4.myhuaweicloud.com/xbh/acc-app-linux-amd64:1.3.2-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/acc-app-linux-arm64:1.3.2-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/ai-fund-report-app:1.0.0-dev \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-agent:1.3.4-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-agent:1.3.8 \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-agent:1.3.8-dev_soft_outline \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-agent:1.3.8-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-agent:1.3.9 \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-agent:1.3.9-dev_soft_outline \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-agent:1.3.9-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-agent:1.5.0-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-agent-linux-amd64:1.2.10-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-agent-linux-amd64:1.3.4-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-agent-linux-amd64:1.3.7 \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-agent-linux-arm64:1.2.10-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-agent-linux-arm64:1.3.4-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-agent-linux-arm64:1.3.7 \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-audio:1.3.4-master \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-audio:1.3.5 \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-audio:1.3.5-dev-onnx \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-audio:1.3.5-master \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-audio:1.3.5-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-audio:1.3.6-dev-onnx-runtime \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-audio-linux-amd64:1.5.0-dev-onnx \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-business-gateway-linux-amd64:1.3.5 \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-business-gateway-linux-amd64:1.3.8 \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-business-gateway-linux-amd64:1.3.9 \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-business-gateway-linux-amd64:1.5.0-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-business-gateway-linux-amd64:1.5.1-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-business-gateway-linux-amd64:1.5.6 \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-business-gateway-linux-arm64:1.3.5 \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-business-gateway-linux-arm64:1.3.8 \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-business-gateway-linux-arm64:1.3.8-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-business-gateway-linux-arm64:1.3.9 \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-business-gateway-linux-arm64:1.3.9-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-business-gateway-linux-arm64:1.5.0-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-business-gateway-linux-arm64:1.5.1-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-business-gateway-linux-arm64:1.5.6 \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-toolbox:1.0.2 \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-toolbox:1.0.3 \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-toolbox:1.0.5-ocr-llm \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-toolbox:1.0.6 \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-toolbox:1.0.7 \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-toolbox:1.0.9 \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-toolbox:1.1.0 \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-uc:1.3.3-origin-dev-originversion-20260527 \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-uc:1.3.6 \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-uc:1.3.8-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-uc:1.5.0-dev-user-init \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-uc:1.5.0-dev-xbox \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-uc-linux-amd64:1.3.5-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-uc-linux-amd64:1.3.6 \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-uc-linux-amd64:1.3.6-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-uc-linux-amd64:1.3.7 \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-uc-linux-amd64:1.3.8 \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-uc-linux-amd64:1.3.8-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-uc-linux-amd64:1.3.9-beihai-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-uc-linux-amd64:1.3.9-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-uc-linux-amd64:1.5.0-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-uc-linux-amd64:1.5.1-beihai-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-uc-linux-amd64:1.5.2 \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-uc-linux-arm64:1.3.5-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-uc-linux-arm64:1.3.6 \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-uc-linux-arm64:1.3.6-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-uc-linux-arm64:1.3.7 \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-uc-linux-arm64:1.3.8 \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-uc-linux-arm64:1.3.8-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-uc-linux-arm64:1.3.9-beihai-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-uc-linux-arm64:1.3.9-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-uc-linux-arm64:1.5.0-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-uc-linux-arm64:1.5.1-beihai-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/cube-uc-linux-arm64:1.5.2 \
  swr.cn-north-4.myhuaweicloud.com/xbh/law-app:1.3.3-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/law-app-linux-amd64:1.3.6 \
  swr.cn-north-4.myhuaweicloud.com/xbh/law-app-linux-amd64:1.3.6-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/law-app-linux-amd64:1.3.7-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/law-app-linux-amd64:1.3.8 \
  swr.cn-north-4.myhuaweicloud.com/xbh/law-app-linux-arm64:1.3.6 \
  swr.cn-north-4.myhuaweicloud.com/xbh/law-app-linux-arm64:1.3.6-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/law-app-linux-arm64:1.3.7-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/law-app-linux-arm64:1.3.8 \
  swr.cn-north-4.myhuaweicloud.com/xbh/llmrunner-amd-linux-amd64:1.0.2 \
  swr.cn-north-4.myhuaweicloud.com/xbh/llmrunner-mthreads-linux-arm64:1.0.0-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/luya:1.0.0-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/luya:1.0.1-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/luya:1.0.1.xdy-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/luya:1.0.3-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/luya:1.5.0 \
  swr.cn-north-4.myhuaweicloud.com/xbh/luya:1.5.0-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/luya:1.5.0-test-amd64 \
  swr.cn-north-4.myhuaweicloud.com/xbh/luya:1.5.1-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/luya:1.5.2-amd64 \
  swr.cn-north-4.myhuaweicloud.com/xbh/luya:1.5.3-amd64 \
  swr.cn-north-4.myhuaweicloud.com/xbh/luya:1.5.3-test-amd64 \
  swr.cn-north-4.myhuaweicloud.com/xbh/luya:1.5.3.1-test-amd64 \
  swr.cn-north-4.myhuaweicloud.com/xbh/luya:1.5.4-amd64 \
  swr.cn-north-4.myhuaweicloud.com/xbh/luya:1.5.4-test-amd64 \
  swr.cn-north-4.myhuaweicloud.com/xbh/luya:1.5.5-amd64 \
  swr.cn-north-4.myhuaweicloud.com/xbh/luya:1.5.5-test-amd64 \
  swr.cn-north-4.myhuaweicloud.com/xbh/luya:1.5.6-amd64 \
  swr.cn-north-4.myhuaweicloud.com/xbh/luya:1.5.6-test-amd64 \
  swr.cn-north-4.myhuaweicloud.com/xbh/luya:1.5.6-wd-dev-1.5.6-amd64 \
  swr.cn-north-4.myhuaweicloud.com/xbh/luya:1.5.7-amd64 \
  swr.cn-north-4.myhuaweicloud.com/xbh/luya:1.5.7-dev-agent-1.5.7-amd64 \
  swr.cn-north-4.myhuaweicloud.com/xbh/luya:1.5.7-test-amd64 \
  swr.cn-north-4.myhuaweicloud.com/xbh/luya:1.5.7-wd-dev-1.5.7-amd64 \
  swr.cn-north-4.myhuaweicloud.com/xbh/luya:1.5.8-amd64 \
  swr.cn-north-4.myhuaweicloud.com/xbh/luya:1.5.8-dev-agent-1.5.8-amd64 \
  swr.cn-north-4.myhuaweicloud.com/xbh/luya:1.5.8-f2-fix-memory-compression-amd64 \
  swr.cn-north-4.myhuaweicloud.com/xbh/luya:1.5.8-f3-fix-memory-compression-amd64 \
  swr.cn-north-4.myhuaweicloud.com/xbh/luya:1.5.8-f4-fix-memory-compression-amd64 \
  swr.cn-north-4.myhuaweicloud.com/xbh/luya:1.5.8-fund-fix-memory-compression-amd64 \
  swr.cn-north-4.myhuaweicloud.com/xbh/luya:1.5.8-sp-sq-agent-system-prompt-opt-amd64 \
  swr.cn-north-4.myhuaweicloud.com/xbh/luya:1.5.8-spo-sq-agent-system-prompt-opt-amd64 \
  swr.cn-north-4.myhuaweicloud.com/xbh/luya:1.5.8-sq-agent-system-prompt-opt-amd64 \
  swr.cn-north-4.myhuaweicloud.com/xbh/luya:1.5.8-sq-agent-system-prompt-opt-with-1.5.8-amd64 \
  swr.cn-north-4.myhuaweicloud.com/xbh/luya:1.5.8-test-amd64 \
  swr.cn-north-4.myhuaweicloud.com/xbh/luya:1.5.9-wd-dev-1.5.9-amd64 \
  swr.cn-north-4.myhuaweicloud.com/xbh/luya:1.6.0-amd64 \
  swr.cn-north-4.myhuaweicloud.com/xbh/luya:1.6.0-fix-market-agent_skill-install-amd64 \
  swr.cn-north-4.myhuaweicloud.com/xbh/luya:1.6.1-fix-api-conflict-amd64 \
  swr.cn-north-4.myhuaweicloud.com/xbh/luya:1.6.1-wd-dev-1.6.1-amd64 \
  swr.cn-north-4.myhuaweicloud.com/xbh/luya:1.6.1-xdy3-test-dev-agent-1.6.1-amd64 \
  swr.cn-north-4.myhuaweicloud.com/xbh/luya-linux-amd64:1.0.1 \
  swr.cn-north-4.myhuaweicloud.com/xbh/luya-linux-amd64:1.0.2-arm64-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/luya-linux-amd64:1.1.0-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/luya-linux-amd64:1.5.0-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/luya-linux-arm64:1.0.1 \
  swr.cn-north-4.myhuaweicloud.com/xbh/luya-linux-arm64:1.0.2-arm64-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/luya-linux-arm64:1.1.0-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/luya-linux-arm64:1.5.0-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr:1.3.4-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr:1.3.4-test-cloud \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr:1.3.5-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr:1.3.5-test-cloud \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr:1.3.6-test-cloud \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-amd64:0.0.9-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-amd64:1.3.3 \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-amd64:1.3.6-test-cloud \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-amd64:1.3.7-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-amd64:1.3.8 \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-amd64:1.3.9 \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-amd64:1.3.9-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-amd64:1.4.0 \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-amd64:1.4.1 \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-amd64:1.4.2 \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-amd64:1.4.2-cloud \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-amd64:1.4.2-fix-installbug-20260609 \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-amd64:1.4.3 \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-amd64:1.4.3-cloud \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-amd64:1.4.4 \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-amd64:1.4.5 \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-amd64:1.5.0-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-amd64:1.5.1-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-amd64:1.5.2-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-amd64:1.5.3-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-amd64:1.5.4-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-amd64:1.5.5 \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-amd64:1.5.5-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-amd64:1.5.6 \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-amd64:1.5.6-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-amd64:1.5.7 \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-amd64:1.6.1-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-arm64:0.0.9-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-arm64:1.3.3 \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-arm64:1.3.6-test-cloud \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-arm64:1.3.7-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-arm64:1.3.8 \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-arm64:1.3.9 \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-arm64:1.3.9-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-arm64:1.4.0 \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-arm64:1.4.1 \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-arm64:1.4.2 \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-arm64:1.4.2-cloud \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-arm64:1.4.2-fix-installbug-20260609 \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-arm64:1.4.3 \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-arm64:1.4.3-cloud \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-arm64:1.4.4 \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-arm64:1.4.5 \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-arm64:1.5.0-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-arm64:1.5.1-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-arm64:1.5.2-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-arm64:1.5.3-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-arm64:1.5.4-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-arm64:1.5.5 \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-arm64:1.5.5-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-arm64:1.5.6 \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-arm64:1.5.6-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-arm64:1.5.7 \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-lolr-linux-arm64:1.6.1-test \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-robot:1.0-13182650cc \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-robot:1.0-2380a65c09 \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-robot:1.0-37443aaa26 \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-robot:1.0-41d712307c \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-robot:1.0-499a83313e \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-robot:1.0-6a2a0fc869 \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-robot:1.0-6fb6b6f9c8 \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-robot:1.0-8527760e44 \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-robot:1.0-a16d56b276 \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-robot:1.0-ae2faafed5 \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-robot:1.0-bca1ef1a99 \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-robot:1.0-c1ff482c27 \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-robot:1.0-c5acf2da07 \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-robot:1.0-c6341f9e9f \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-robot:1.0-e557fd5692 \
  swr.cn-north-4.myhuaweicloud.com/xbh/ns-robot:1.0-eaa84f3822 \
  2>/dev/null || true

echo ""
echo "Done! Remaining images:"
docker images | wc -l
